language: c

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

script: autoconf && ./configure && make && make check && (cd test-dev; autoconf && ./configure && make) && make -f Makefile.lite

matrix:
  include:
    # Linux distributions

    - os: linux
      dist: focal

    - os: linux
      dist: bionic

    - os: linux
      dist: precise

    # mingw32 cross compilation

    - os: linux
      compiler: x86_64-w64-mingw32-gcc
      script: autoconf && ./configure --host=x86_64-w64-mingw32 && make
      dist: focal
      addons:
        apt:
          packages:
            - gcc-mingw-w64-base
            - binutils-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
            - gcc-mingw-w64

    # windows with visual studio 2017

    - os: windows
      language: c
      compiler: cl
      script:
        - export PATH="C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Current\Bin":$PATH
        - nmake -f Makefile.vc
        - nmake -f Makefile.vc check

#
#    #  no need to add LD_PRELOAD=$(clang -print-file-name=libclang_rt.asan-x86_64.so) ?

#    - os: linux
#      dist: focal
#      compiler: clang
#      env: CFLAGS="-fsanitize=address" LDFLAGS="-fsanitize=address"
#      script: autoconf && ./configure && make && make check && (cd test-dev; autoconf && ./configure && make)
#
#    - os: linux
#      dist: focal
#      compiler: clang
#      env: CFLAGS="-fsanitize=memory" LDFLAGS="-fsanitize=memory"
#      script: autoconf && ./configure && make && make check && (cd test-dev; autoconf && ./configure && make)

